dateModified: 1551615305
email:
  fromEmail: comphanny@example.com
  fromName: Comphanny
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  fd1f04b0-5c66-4a29-8d77-84e8361d1292:
    name: Common
imageTransforms:
  3b5b0809-6c19-439f-949a-64e023128ad7:
    format: null
    handle: thumbBanner
    height: '195'
    interlace: none
    mode: crop
    name: 'Thumb Banner'
    position: center-center
    quality: null
    width: '347'
  65cdef0b-c238-4005-b65a-4ba831221824:
    format: null
    handle: thumbBannerLg
    height: '302'
    interlace: none
    mode: crop
    name: 'Thumb Banner Large'
    position: center-center
    quality: null
    width: '538'
  9df14a11-c54f-4004-8019-0a59a11ba789:
    format: null
    handle: profileSm
    height: '155'
    interlace: none
    mode: crop
    name: 'Profile Small'
    position: center-center
    quality: null
    width: '116'
  aabb7f35-70e2-44b9-8ddb-d76430265137:
    format: null
    handle: profileLg
    height: '276'
    interlace: none
    mode: crop
    name: 'Profile Large'
    position: center-center
    quality: null
    width: '369'
  e8607822-82c3-45da-9ff0-d610e946101f:
    format: null
    handle: pageBanner
    height: '624'
    interlace: none
    mode: crop
    name: 'Page Banner'
    position: center-center
    quality: null
    width: '1110'
plugins:
  architect:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.2.2
sections:
  191ff4d9-22bf-4fc1-a47b-1123392d5f47:
    enableVersioning: true
    entryTypes:
      0334a6c4-8346-48b7-94fb-3f80699e785d:
        handle: homepage
        hasTitleField: false
        name: Homepage
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: ''
    handle: homepage
    name: Homepage
    propagateEntries: true
    siteSettings:
      e2d75038-c4ed-417b-8edb-5a1037eaf3b0:
        enabledByDefault: true
        hasUrls: true
        template: index.twig
        uriFormat: /
    type: single
  750379a3-ba67-4a47-a6cc-e9b79bfca59f:
    enableVersioning: true
    entryTypes:
      b9d8c4f7-66f2-4dc3-a6d1-cc8525bf3a89:
        handle: products
        hasTitleField: true
        name: Products
        sortOrder: 1
        titleFormat: null
        titleLabel: Title
    handle: products
    name: Products
    propagateEntries: true
    siteSettings:
      e2d75038-c4ed-417b-8edb-5a1037eaf3b0:
        enabledByDefault: true
        hasUrls: true
        template: products/entry
        uriFormat: 'products/{slug}'
    type: channel
  82a69350-9107-4234-a575-59ba64b45ed5:
    enableVersioning: true
    entryTypes:
      afbf0700-9b7e-4719-b604-c41c2ef56d0f:
        handle: contact
        hasTitleField: false
        name: Contact
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: null
    handle: contact
    name: Contact
    propagateEntries: true
    siteSettings:
      e2d75038-c4ed-417b-8edb-5a1037eaf3b0:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: contact
    type: single
  942fad99-0dfc-48e7-a565-fcfba401a8a3:
    enableVersioning: true
    entryTypes:
      66a2d7b7-9d49-4844-bd2e-b8eb9d7161f3:
        handle: company
        hasTitleField: true
        name: Company
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: company
    name: Company
    propagateEntries: true
    siteSettings:
      e2d75038-c4ed-417b-8edb-5a1037eaf3b0:
        enabledByDefault: true
        hasUrls: true
        template: company/entry
        uriFormat: 'company/{slug}'
    type: channel
siteGroups:
  63404c82-7eba-42b0-9ed2-01ffc278562e:
    name: Comphanny
sites:
  e2d75038-c4ed-417b-8edb-5a1037eaf3b0:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: Comphanny
    primary: true
    siteGroup: 63404c82-7eba-42b0-9ed2-01ffc278562e
    sortOrder: 1
system:
  edition: solo
  live: true
  name: Comphanny
  schemaVersion: 3.1.25
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
volumes:
  4819b2f4-6231-466c-908f-96633885cd58:
    handle: profiles
    hasUrls: true
    name: Profiles
    settings:
      path: /Users/davina/Developer/proj-comphanny-cms/web/uploads/profiles
    sortOrder: 3
    type: craft\volumes\Local
    url: //proj-comphanny-cms.test/uploads/profiles
  c5545297-3c20-42eb-9d7a-6e914b34ecba:
    handle: about
    hasUrls: true
    name: About
    settings:
      path: /Users/davina/Developer/proj-comphanny-cms/web/uploads/about
    sortOrder: '1'
    type: craft\volumes\Local
    url: //proj-comphanny-cms.test/uploads/about
  f15fa10d-026b-4f9c-88f5-ca84334c8615:
    handle: products
    hasUrls: true
    name: Products
    settings:
      path: /Users/davina/Developer/proj-comphanny-cms/web/uploads/products
    sortOrder: 2
    type: craft\volumes\Local
    url: //proj-comphanny-cms.test/uploads/products
